export const documentTypes = [
  'Allotment (SUB-ARO/SARO)', 'Allotment/NCA Request', 'Application Documents',
  'Application for Leave (Abroad)', 'Application for Leave (Local)', 'Audit Report',
  'BIR Form 2305', 'DepEd Memorandum', 'DepEd Order', 'Division Memorandum',
  'Document Review and Approval Form (DRAF)', 'Itinerary of Travel', 'Letter',
  'Liquidation Report', 'List of Officials & Employees Granted Step Increment',
  'Loan Confirmation', 'Memorandum', 'Modification of Fund (MAF/APSA)',
  'Notice of Salary Adjustment', 'Obligation Request and Status', 'Office Memorandum',
  'Office Order', 'Payroll', 'PPMP/APP/ASB', 'Project Proposal', 'Purchase Order',
  'Purchase Request', 'Regional Memorandum', 'Reports', 'Request for Quotation',
  'Request Form', 'Statement of Account', 'SUB-ARO/SARO', 'Travel Order', 'Unclassified'
];

export const purposes = [
  'Appropriate Actions', 'Comment/Recommend', 'Coordinate',
  'Evaluate/Review', 'File', 'For approval', 'For endorsement', 'For signature',
  'Information/Reference', 'Reply for signature of the SDS'
];

export const releaseToOptions = [
  'Personnel: Arlo Carl Figuracion',
  'Unit: Accounting Section', 'Unit: Administrative Section', 'Unit: BAC Office',
  'Unit: Budget Section', 'Unit: Cash Section', 'Unit: CID', 'Unit: Dental Unit',
  'Unit: Disaster Risk Reduction and Management Unit', 'Unit: ICT Section',
  'Unit: Learning Resource Management Section', 'Unit: Legal Section', 'Unit: Medical Unit',
  'Unit: Office of the ASDS', 'Unit: Office of the SDS', 'Unit: Payroll',
  'Unit: Personnel Section', 'Unit: Records Section', 'Unit: SGOD', 'Unit: Supply Section',
  'School: Agripino P. Santos ES', 'School: Alipio N. Ignacio MES', 'School: Amarosa ES',
  'School: Bacsil ES', 'School: Balacad ES', 'School: Balatong ES', 'School: Barit ES',
  'School: Buttong ES', 'School: Caaoacan ES', 'School: Caaoacan HS', 'School: Cabeza ES',
  'School: Calayab ES', 'School: Casili ES', 'School: Cataban ES', 'School: Cavit-Araniw ES',
  'School: Darayday ES', 'School: Don Galicano R. Rafales MES', 'School: DWAT Radio Station',
  'School: Eulalio F. Siazon MES', 'School: Faustino Reyes MES', 'School: Gabaldon ES',
  'School: Gabu ES', 'School: Gabu NHS', 'School: Ilocos Norte College of Arts & Trades',
  'School: Ilocos Norte National High School', 'School: Ilocos Norte Regional School of Fisheries',
  'School: Lagui-Sail ES', 'School: Laoag CES', 'School: Navotas ES', 'School: Pila ES',
  'School: Plaridel ES', 'School: RCGF National Science High School', 'School: Roque B. Ablan MES',
  'School: Salet ES', 'School: San Mateo IS', 'School: Shamrock ES', 'School: Sta. Maria ES',
  'School: Sto. Nino ES', 'School: Suyo ES', 'School: Tangid ES', 'School: Vira ES',
  'Private School: AIE College - Laoag, Inc.',
  'Private School: AMA Computer College-Laoag City Inc.',
  'Private School: Atty. Sixto S. Pedro Memorial Christian Academy',
  'Private School: Bible Believing Baptist Church Educational Ministries Foundation, Inc.',
  'Private School: Caterpillar Centre for Early Learners, Inc.',
  'Private School: Data Center College of the Philippines of Laoag City',
  'Private School: Divine Word College Laoag',
  'Private School: Emmanuel Fundamental Baptist Learning Center',
  'Private School: Holy Spirit Academy of Laoag',
  'Private School: Ilocos Norte Adventist School Inc.',
  'Private School: International School of the Arts, the Languages, and the Academe',
  'Private School: Kids\' Kollege, Inc.',
  'Private School: Laoag Four Square Kindergarten Sch. Inc.',
  'Private School: Maranatha Christian School of Laoag, Inc.',
  'Private School: MRS Dayspring Christian School',
  'Private School: Northern Christian College Basic Education School',
  'Private School: Northside Bible Baptist Academy, Inc.',
  'Private School: Northwestern University',
  'Private School: Our Saviour\'s Foundation, Inc.',
  'Private School: Padre Annibale Integrated School, Inc.',
  'Private School: Saved by Grace Christian Academy, Inc.',
  'Private School: St. Joseph High School of Laoag, Inc.',
  'Private School: St. Mary\'s Seminary',
  'Private School: St. Santiago School Foundation, Inc.',
  'Private School: STI College - Laoag',
  'Private School: The Living Gates of Praise Christian School, Inc.',
  'Private School: The Salvation Army Educational Services, Inc.',
  'Agency: Mariano Marcos State University - Laoag City'
];